### ISSUE TITLE
imports renamed?

### ISSUE THREAD

**Issue by sneakers-the-rat** [datajoint/workflow-session#10]
these imports seem to be singular rather than plural now? (`element_lab` rather than `elements_lab`)

https://github.com/datajoint/workflow-animal/blob/fb545a68e3d501b7852b6ec1f12cb5093f30239c/workflow_animal/pipeline.py#L2-L5

**Comment by CBroz1** [comment]
Thanks for pointing that out! We have a revision underway for this workflow, so this repo will get a bit of an overhaul soon.
