### ISSUE TITLE
No examples of `genotyping` schema provided in `workflow-animal` notebook

### ISSUE THREAD

**Issue by CBroz1** [datajoint/workflow-session#12]

**Comment by CBroz1** [comment]
@iamamutt - Do you know of any good example data with which I could populate the `genotyping` schema?

**Comment by kabilar** [comment]
Add ingestion steps for allele and genotyping data to `ingest.py`.

**Comment by CBroz1** [comment]
I now have access to a PyRAT database with this kind of information, but I need permission to copy it

**Comment by CBroz1** [comment]
Closed by #23
